apiVersion: v1
kind: Service
metadata:
  name: custom-coredns
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: dns
      port: 53
      targetPort: 53
      nodePort: 31160
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      nodePort: 31160
      protocol: TCP
  selector:
    k8s-app: custom-coredns

