apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        log
        errors
        hosts {
          192.168.0.54 grafana.lab.local flask.lab.local
            fallthrough
        }
        forward . 8.8.8.8
    }

